{
 "title": "Frontend",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(service_requests,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(service_requests[5m]) OR on() vector(0))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (rate(service_errors[5m]) OR on() vector(0))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(service_requests[5m]) OR on() vector(0))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors Break Down",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(temporal_service_errors[5m])) by (temporal_error_kind)",
     "legendFormat": "{{temporal_error_kind}}"
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(service_latency_bucket[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Request Vs Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(persistence_requests[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (rate(persistence_errors[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(persistence_requests[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors Break Down",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(persistence_errors[5m]) OR on() vector(0))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Persistence Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(persistence_latency_bucket[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "History Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Requests Vs Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_requests{service_role=\"history\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(rate(client_errors{service_role=\"history\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(client_requests{service_role=\"history\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors By Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(client_errors{service_role=\"history\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(client_latency_bucket{service_role=\"history\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Matching Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Requests Vs Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_requests{service_role=\"matching\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(rate(client_errors{service_role=\"matching\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(client_requests{service_role=\"matching\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors By Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(client_errors{service_role=\"matching\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Matching Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(client_latency_bucket{service_role=\"matching\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}