{
 "title": "History",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(service_requests,cluster)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(service_requests,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mutable State Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mutable State Cache Operation - Non Current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_requests{cluster=\"$cluster\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[1m]))",
       "legendFormat": "cache_requests"
      },
      {
       "expr": "sum(rate(cache_errors{cluster=\"$cluster\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[1m]))",
       "legendFormat": "cache_failures"
      },
      {
       "expr": "sum(rate(cache_miss{cluster=\"$cluster\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[1m]))",
       "legendFormat": "cache_miss"
      }
     ]
    },
    {
     "title": "Mutable State Cache Operation - Current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_requests{cluster=\"$cluster\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[1m]))",
       "legendFormat": "cache_requests"
      },
      {
       "expr": "sum(rate(cache_errors{cluster=\"$cluster\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[1m]))",
       "legendFormat": "cache_failures"
      },
      {
       "expr": "sum(rate(cache_miss{cluster=\"$cluster\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[1m]))",
       "legendFormat": "cache_miss"
      }
     ]
    },
    {
     "title": "Mutable State Cache P* Lock Acquire Latency - Non Current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(cache_latency_bucket{cluster=\"$cluster\",service=\"$service\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[1m])) by (le))",
       "legendFormat": "P50 Latency"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(cache_latency_bucket{cluster=\"$cluster\",service=\"$service\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[1m])) by (le))",
       "legendFormat": "P95 Latency"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cache_latency_bucket{cluster=\"$cluster\",service=\"$service\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[1m])) by (le))",
       "legendFormat": "P99 Latency"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(cache_latency_bucket{cluster=\"$cluster\",service=\"$service\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[1m])) by (le))",
       "legendFormat": "P99.9 Latency"
      }
     ]
    },
    {
     "title": "Mutable State Cache P* Lock Acquire Latency - Current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(cache_latency_bucket{cluster=\"$cluster\",service=\"$service\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[1m])) by (le))",
       "legendFormat": "P50 Latency"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(cache_latency_bucket{cluster=\"$cluster\",service=\"$service\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[1m])) by (le))",
       "legendFormat": "P95 Latency"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cache_latency_bucket{cluster=\"$cluster\",service=\"$service\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[1m])) by (le))",
       "legendFormat": "P99 Latency"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(cache_latency_bucket{cluster=\"$cluster\",service=\"$service\",cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[1m])) by (le))",
       "legendFormat": "P99.9 Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Events Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events Cache - Overview",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation)(rate(cache_requests{cluster=\"$cluster\",service=\"$service\",cache_type=\"events\"}[1m]))"
      },
      {
       "expr": "sum by (operation) (rate(cache_miss{cluster=\"$cluster\",cache_type=\"events\"}[1m]))",
       "legendFormat": "{{ operation }} - cache_miss"
      }
     ]
    },
    {
     "title": "Get Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation)(rate(cache_requests{cluster=\"$cluster\",service=\"$service\",cache_type=\"events\", operation=\"EventsCacheGetEvent\"}[1m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum by (operation)(rate(cache_miss{cluster=\"$cluster\",cache_type=\"events\", operation=\"EventsCacheGetEvent\"}[1m]))",
       "legendFormat": "cache_miss"
      },
      {
       "expr": "sum by (operation)(rate(cache_errors{cluster=\"$cluster\",cache_type=\"events\", operation=\"EventsCacheGetEvent\"}[1m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Get Events Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cache_latency_bucket{cluster=\"$cluster\",service=\"$service\",cache_type=\"events\", operation=\"EventsCacheGetEvent\"}[1m])) by (le))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "Put Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_requests{cluster=\"$cluster\",service=\"$service\",cache_type=\"events\", operation=\"EventsCachePutEvent\"}[1m]))",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "Put Events Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cache_latency_bucket{cluster=\"$cluster\",service=\"$service\",cache_type=\"events\", operation=\"EventsCachePutEvent\"}[1m])) by (le))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "Get Events From Store",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_requests{cluster=\"$cluster\",service=\"$service\",cache_type=\"events\", operation=\"EventsCacheGetFromStore\"}[1m]))",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "Get Events From Store Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cache_latency_bucket{cluster=\"$cluster\",service=\"$service\",cache_type=\"events\", operation=\"EventsCacheGetFromStore\"}[1m])) by (le))",
       "legendFormat": "latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow Task Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Task Break Down",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(schedule_activity_command{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "schedule_activity"
      },
      {
       "expr": "sum(rate(complete_workflow_command{ operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "complete_workflow"
      },
      {
       "expr": "sum(rate(fail_workflow_command{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "fail_workflow"
      },
      {
       "expr": "sum(rate(cancel_workflow_command{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "cancel_workflow"
      },
      {
       "expr": "sum(rate(start_timer_command{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "start_timer"
      },
      {
       "expr": "sum(rate(cancel_activity_command{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "cancel_activity"
      },
      {
       "expr": "sum(rate(cancel_timer_command{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "cancel_timer"
      },
      {
       "expr": "sum(rate(record_marker_command{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "record_marker"
      },
      {
       "expr": "sum(rate(cancel_external_workflow_command{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "cancel_external_workflow"
      },
      {
       "expr": "sum(rate(continue_as_new_command{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "continue_as_new"
      },
      {
       "expr": "sum(rate(signal_external_workflow_command{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "signal_external_workflow"
      },
      {
       "expr": "sum(rate(upsert_workflow_search_attributes_command{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "upsert_searchable_attributes"
      },
      {
       "expr": "sum(rate(child_workflow_command{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "child_workflow"
      }
     ]
    },
    {
     "title": "Sticky Vs Non Sticky",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(service_requests{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "commands_complete"
      },
      {
       "expr": "sum(rate(complete_workflow_task_sticky_enabled_count{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "sticky_tasks"
      },
      {
       "expr": "sum(rate(complete_workflow_task_sticky_disabled_count{operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "non_sticky_tasks"
      }
     ]
    },
    {
     "title": "Failed Workflow Task",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(failed_workflow_tasks{temporal_service_type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Empty Workflow Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(empty_completion_commands{temporal_service_type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "empty_decision"
      }
     ]
    },
    {
     "title": "Multiple Complete Workflows",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(multiple_completion_commands{temporal_service_type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[1m]))",
       "legendFormat": "empty_workflow"
      }
     ]
    }
   ]
  }
 ]
}